/**
 * Curated list of popular domains for static /email-security/[domain] pages.
 * Focus: domains people would actually want to check for email spoofing protection.
 */
export const POPULAR_DOMAINS = [
  // ── Email providers (core use case) ────────────────────────────
  "gmail.com",
  "outlook.com",
  "yahoo.com",
  "hotmail.com",
  "aol.com",
  "icloud.com",
  "protonmail.com",
  "proton.me",
  "zoho.com",
  "fastmail.com",
  "tutanota.com",
  "mailfence.com",
  "mailbox.org",
  "gmx.com",
  "mail.com",
  "hushmail.com",
  "yandex.com",
  "mail.ru",

  // ── French ISPs & telecom ──────────────────────────────────────
  "orange.fr",
  "free.fr",
  "sfr.fr",
  "laposte.net",
  "bouyguestelecom.fr",
  "ovh.net",
  "ovh.com",
  "gandi.net",

  // ── French banks ───────────────────────────────────────────────
  "bnpparibas.com",
  "societegenerale.fr",
  "credit-agricole.fr",
  "lcl.fr",
  "banquepopulaire.fr",
  "caisse-epargne.fr",
  "cic.fr",
  "credit-mutuel.fr",
  "boursorama.com",
  "fortuneo.fr",
  "ing.fr",
  "hellobank.fr",
  "labanquepostale.fr",
  "revolut.com",
  "n26.com",

  // ── French e-commerce & services ───────────────────────────────
  "amazon.fr",
  "cdiscount.com",
  "fnac.com",
  "darty.com",
  "leboncoin.fr",
  "vinted.fr",
  "veepee.com",
  "showroomprive.com",
  "leroy-merlin.fr",
  "decathlon.fr",
  "boulanger.com",
  "manomano.fr",
  "backmarket.fr",
  "rakuten.com",

  // ── French government & institutions ───────────────────────────
  "gouv.fr",
  "impots.gouv.fr",
  "ameli.fr",
  "caf.fr",
  "pole-emploi.fr",
  "education.gouv.fr",
  "service-public.fr",
  "legifrance.gouv.fr",
  "ants.gouv.fr",
  "interieur.gouv.fr",

  // ── French education ───────────────────────────────────────────
  "sorbonne-universite.fr",
  "polytechnique.fr",
  "ens.fr",
  "univ-paris-saclay.fr",
  "sciencespo.fr",
  "hec.fr",
  "inria.fr",

  // ── French media ───────────────────────────────────────────────
  "lemonde.fr",
  "lefigaro.fr",
  "liberation.fr",
  "france24.com",
  "tf1.fr",
  "france.tv",
  "radiofrance.fr",

  // ── Global tech ────────────────────────────────────────────────
  "google.com",
  "apple.com",
  "microsoft.com",
  "amazon.com",
  "meta.com",
  "facebook.com",
  "x.com",
  "github.com",
  "linkedin.com",
  "netflix.com",
  "spotify.com",
  "dropbox.com",
  "slack.com",
  "salesforce.com",
  "adobe.com",
  "oracle.com",
  "ibm.com",
  "intel.com",
  "nvidia.com",
  "samsung.com",
  "huawei.com",
  "tiktok.com",
  "snapchat.com",
  "pinterest.com",
  "reddit.com",
  "wikipedia.org",
  "wordpress.com",
  "shopify.com",
  "squarespace.com",
  "wix.com",
  "canva.com",
  "notion.so",
  "figma.com",
  "vercel.com",
  "cloudflare.com",
  "digitalocean.com",
  "aws.amazon.com",
  "heroku.com",

  // ── Global e-commerce ──────────────────────────────────────────
  "ebay.com",
  "alibaba.com",
  "aliexpress.com",
  "etsy.com",
  "walmart.com",
  "target.com",
  "bestbuy.com",
  "ikea.com",
  "zalando.com",
  "asos.com",
  "shein.com",
  "temu.com",

  // ── Global banks & finance ─────────────────────────────────────
  "jpmorgan.com",
  "bankofamerica.com",
  "wellsfargo.com",
  "hsbc.com",
  "barclays.com",
  "deutschebank.com",
  "ubs.com",
  "credit-suisse.com",
  "goldmansachs.com",
  "paypal.com",
  "stripe.com",
  "wise.com",

  // ── Travel & transport ─────────────────────────────────────────
  "airfrance.fr",
  "sncf.com",
  "blablacar.fr",
  "booking.com",
  "airbnb.com",
  "tripadvisor.com",
  "expedia.com",
  "uber.com",
  "lyft.com",
  "ryanair.com",
  "easyjet.com",
  "lufthansa.com",
  "emirates.com",

  // ── Health & insurance (France) ────────────────────────────────
  "doctolib.fr",
  "alan.com",
  "axa.fr",
  "maif.fr",
  "macif.fr",
  "groupama.fr",
  "allianz.fr",
  "harmonie-mutuelle.fr",

  // ── Telecom international ──────────────────────────────────────
  "vodafone.com",
  "t-mobile.com",
  "verizon.com",
  "att.com",
  "bt.com",
  "telstra.com",
  "rogers.com",

  // ── Cybersecurity (relevant for the audience) ──────────────────
  "crowdstrike.com",
  "paloaltonetworks.com",
  "fortinet.com",
  "checkpoint.com",
  "sophos.com",
  "kaspersky.com",
  "norton.com",
  "malwarebytes.com",
  "1password.com",
  "bitwarden.com",
  "lastpass.com",

  // ── Hosting & registrars ───────────────────────────────────────
  "godaddy.com",
  "namecheap.com",
  "ionos.com",
  "hostinger.com",
  "bluehost.com",
  "siteground.com",
  "infomaniak.com",
  "scaleway.com",
  "hetzner.com",

  // ── Education international ────────────────────────────────────
  "harvard.edu",
  "mit.edu",
  "stanford.edu",
  "ox.ac.uk",
  "cam.ac.uk",
  "ethz.ch",

  // ── Government international ───────────────────────────────────
  "gov.uk",
  "europa.eu",
  "who.int",
  "un.org",
  "nato.int",

  // ── Retail & fashion (high check intent) ───────────────────────
  "vinted.com",
  "zara.com",
  "hm.com",
  "uniqlo.com",
  "nike.com",
  "adidas.com",
  "zalando.fr",
  "zalando.de",
  "otto.de",
  "bol.com",
  "allegro.pl",
  "mediamarkt.de",
  "sephora.fr",
  "sephora.com",
  "laredoute.fr",
  "galerieslafayette.com",
  "printemps.com",
  "conforama.fr",
  "but.fr",
  "castorama.fr",
  "ikea.fr",
  "kiabi.com",
  "sezane.com",
  "yvesrocher.fr",
  "vente-privee.com",

  // ── Grocery & supermarkets ─────────────────────────────────────
  "carrefour.fr",
  "auchan.fr",
  "leclerc.com",
  "intermarche.com",
  "monoprix.fr",
  "franprix.fr",
  "lidl.fr",
  "aldi.fr",
  "picard.fr",
  "naturalia.fr",

  // ── SaaS & productivity ────────────────────────────────────────
  "zoom.us",
  "atlassian.com",
  "trello.com",
  "asana.com",
  "monday.com",
  "hubspot.com",
  "mailchimp.com",
  "sendgrid.com",
  "twilio.com",
  "zendesk.com",
  "intercom.com",
  "webflow.com",
  "airtable.com",
  "clickup.com",
  "box.com",
  "calendly.com",
  "typeform.com",
  "docusign.com",
  "miro.com",
  "loom.com",

  // ── Developer & cloud ──────────────────────────────────────────
  "gitlab.com",
  "jetbrains.com",
  "postman.com",
  "mongodb.com",
  "elastic.co",
  "snowflake.com",
  "databricks.com",
  "datadoghq.com",
  "grafana.com",
  "gitpod.io",

  // ── AI ─────────────────────────────────────────────────────────
  "openai.com",
  "anthropic.com",
  "mistral.ai",
  "huggingface.co",
  "perplexity.ai",

  // ── Fintech & crypto ───────────────────────────────────────────
  "qonto.com",
  "klarna.com",
  "monzo.com",
  "coinbase.com",
  "binance.com",
  "kraken.com",
  "etoro.com",
  "tradingview.com",
  "lydia-app.com",
  "sumup.com",
  "shine.fr",
  "swile.co",
  "pennylane.com",
  "spendesk.com",
  "ledger.com",

  // ── International banks ────────────────────────────────────────
  "citi.com",
  "morganstanley.com",
  "americanexpress.com",
  "capitalone.com",
  "santander.com",
  "bbva.com",
  "unicredit.it",
  "intesasanpaolo.com",
  "rabobank.nl",
  "commerzbank.de",

  // ── Telecom (Europe) ───────────────────────────────────────────
  "sosh.fr",
  "red-by-sfr.fr",
  "o2.com",
  "three.co.uk",
  "telekom.de",
  "swisscom.ch",
  "proximus.be",
  "telefonica.com",
  "vodafone.de",
  "orange.com",
  "kpn.com",
  "telenet.be",

  // ── Media & streaming ──────────────────────────────────────────
  "disneyplus.com",
  "max.com",
  "paramountplus.com",
  "canalplus.com",
  "mycanal.fr",
  "deezer.com",
  "soundcloud.com",
  "twitch.tv",
  "dailymotion.com",
  "lequipe.fr",
  "leparisien.fr",
  "ouest-france.fr",
  "20minutes.fr",
  "mediapart.fr",
  "bfmtv.com",
  "francetvinfo.fr",
  "nytimes.com",
  "theguardian.com",
  "bbc.co.uk",
  "cnn.com",
  "reuters.com",
  "bloomberg.com",

  // ── Travel & mobility ──────────────────────────────────────────
  "kayak.com",
  "skyscanner.net",
  "hotels.com",
  "lastminute.com",
  "opodo.fr",
  "transavia.com",
  "accor.com",
  "hilton.com",
  "marriott.com",
  "flixbus.fr",
  "trainline.com",
  "getaround.com",
  "bolt.eu",
  "klm.com",
  "britishairways.com",

  // ── Gaming ─────────────────────────────────────────────────────
  "steampowered.com",
  "epicgames.com",
  "playstation.com",
  "xbox.com",
  "nintendo.com",
  "ubisoft.com",
  "ea.com",
  "riotgames.com",
  "roblox.com",
  "discord.com",

  // ── Food delivery ──────────────────────────────────────────────
  "ubereats.com",
  "deliveroo.fr",
  "just-eat.fr",
  "doordash.com",
  "hellofresh.com",

  // ── Online learning ────────────────────────────────────────────
  "coursera.org",
  "udemy.com",
  "duolingo.com",
  "khanacademy.org",
  "openclassrooms.com",

  // ── Insurance (France) ─────────────────────────────────────────
  "matmut.fr",
  "gmf.fr",
  "maaf.fr",
  "april.fr",
  "direct-assurance.fr",

  // ── Disposable email (educational: weak security examples) ─────
  "guerrillamail.com",
  "mailinator.com",
  "yopmail.com",
  "tempmail.com",
  "throwaway.email",
] as const;

export type PopularDomain = (typeof POPULAR_DOMAINS)[number];
